### ISSUE TITLE
Ensure installation works with ArgoCD

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-helm-charts#42]
For ArgoCD, we do have additional hook configuration annotations. We never tested, but we got a report it's broken.

> Deploying RHTPA 2 via the helm chart is pretty straightforward however I did run into one bug with respect to Argo CD. The RHTPA Helm chart puts the Importer in a sync wave before the script that creates the importer tables in the database, as a result the Importer Deployment fails and the GitOps deployment never proceeds further.

The proposed solution is to change the importer to "sync wave 5":

```yaml
patches:
 - patch: |
     - op: add
       path: /metadata/annotations/argocd.argoproj.io~1sync-wave
       value: "5"
   target:
     kind: Deployment
     name: importer
```
